// Generates app/tokens.css from the design system in ../docs/design.md.
// Run: npm run tokens  (the design.md is the source of truth, never edit tokens.css)
import { readFileSync, writeFileSync } from 'node:fs';
import { parse } from 'yaml';

const SRC = new URL('../docs/design.md', import.meta.url);
const OUT = new URL('../app/tokens.css', import.meta.url);

const front = readFileSync(SRC, 'utf8').split(/^---$/m)[1];
const d = parse(front);

const lines = [];
const push = (name, value) => lines.push(`  ${name}: ${value};`);

for (const [k, v] of Object.entries(d.colors ?? {})) push(`--color-${k}`, v);
lines.push('');
for (const [k, t] of Object.entries(d.typography ?? {})) {
  push(`--text-${k}`, t.fontSize);
  if (t.lineHeight != null) push(`--text-${k}--line-height`, t.lineHeight);
  if (t.fontWeight != null) push(`--text-${k}--font-weight`, t.fontWeight);
  if (t.letterSpacing != null) push(`--text-${k}--letter-spacing`, t.letterSpacing);
}
lines.push('');
for (const [k, v] of Object.entries(d.rounded ?? {})) push(`--radius-${k}`, v);
lines.push('');
for (const [k, v] of Object.entries(d.spacing ?? {})) push(`--spacing-${k}`, v);

const css = `/* Generated by scripts/tokens.mjs from docs/design.md (version: ${d.version}). Do not edit. */
@theme {
${lines.join('\n')}
}
`;
writeFileSync(OUT, css);
console.log(`tokens.css written: ${Object.keys(d.colors ?? {}).length} colours, ${Object.keys(d.typography ?? {}).length} type styles`);
